name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: crates  
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust 1.86.0
        uses: actions-rs/toolchain@v1   
        with:
          toolchain: 1.86.0
          components: rustfmt, clippy
          override: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Clippy check
        run: cargo clippy -- -D warnings

      - name: Run tests
        run: cargo test

      - name: Build
        run: cargo build --release

    #  - name: Build with serde feature
    #    run: cargo build --release --features serde